#!/usr/bin/with-contenv bash

# Create log file
if [ ! -f "/var/log/wikmd.log" ]
then
  touch /var/log/wikmd.log
  chown abc:abc /var/log/wikmd.log
  chmod 666 /var/log/wikmd.log
fi

# if /wiki isn't mounted create it
if [ ! -d "/wiki" ]
then
  # create directories
  mkdir -p /wiki
  chown -R abc:abc /wiki
  chown -R abc:abc /wiki/*
fi

# If /wiki exists and is empty, populate it with the examples
if [ -d "/wiki" ] && [ ! "$(ls -A /wiki)" ]
then
  # copy examples
  cp /app/wikmd/wiki/*.md /wiki/.

  # permissions
  chown -R abc:abc /wiki/*
  chown -R abc:abc /wiki
fi

chown -R abc:abc /app/wikmd/plugins/*
chown -R abc:abc /app/wikmd/plugins
chown -R abc:abc /app/wikmd/static/*
chown -R abc:abc /app/wikmd/static
