#!/usr/bin/with-contenv bash

touch /var/log/wikmd.log
chown abc:abc /var/log/wikmd.log
chown -R abc:abc /wiki

# if /wiki isn't mounted create it and populate it with the examples
if [ ! -d "/wiki" ]
then
  # create directories
  mkdir -p /wiki

  # copy examples
  cp /app/wikmd/wiki/*.md /wiki/.

  # permissions
  chown -R abc:abc /wiki
  chown -R abc:abc /app
fi

